### ISSUE TITLE
mkdir function

### ISSUE THREAD

**Issue by timchurchard** [moov-io/go-ftp#22]
Please could the UploadFile function create directories. Or could you expose the FTP mkdir

**Comment by adamdecaf** [comment]
We probably can, but with the underlying libraries need to chdir it might be unable to fully resolve some relative paths to mkdir.

**Comment by adamdecaf** [comment]
Can you try out the branch before we merge/release? Some servers/permission setups don't allow mkdir so we have to hide it behind a config option (and to keep the behavior stable).

```
go get github.com/moov-io/go-ftp@feat-upload-can-mkdir
```

**Comment by timchurchard** [comment]
Hi, thank you for working on the issues I raised so quickly. I've tested the feat-upload-can-mkdir but I'm getting `"FTP: mkdir 2025/03/13/ (from /) failed: 550 Create directory operation failed."` I've been asked to send files to FTP partitioned by date as above, and I'm testing with this docker compose. If I connect from the shell to this container I am able to mkdir and chdir.

```
vsftpd:
    image: fauria/vsftpd:latest
    container_name: vsftpd
    environment:
      FTP_USER: ftpuser
      FTP_PASS: ftppass
```
